apiVersion: v1
kind: Service
metadata:
  name: evidence
  namespace: evidra
spec:
  selector:
    app: evidence
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: grpc
    port: 9083
    targetPort: 9083
