apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: evidra
spec:
  selector:
    app: identity
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: grpc
    port: 9081
    targetPort: 9081
