apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: evidra

resources:
- namespace.yaml
- configmap.yaml
- identity-deployment.yaml
- identity-service.yaml
- questionnaire-deployment.yaml
- questionnaire-service.yaml
- questionnaire-worker-deployment.yaml
- evidence-deployment.yaml
- evidence-service.yaml
- orchestrator-deployment.yaml
- orchestrator-service.yaml
- orchestrator-worker-deployment.yaml
- audit-deployment.yaml
- audit-service.yaml
- ingress.yaml
